language: java

os:
- linux
#- osx

jobs:
  include:
    - stage: lab1
      jdk: openjdk13
      env: FOLDER=lab1
      script:
        - cd $FOLDER
        - mvn package
    - stage: lab2
      jdk: openjdk13
      env: FOLDER=lab2
      script:
        - cd $FOLDER
        - mvn package
    - stage: lab3
      jdk: openjdk13
      env: FOLDER=lab3
      script:
        - cd $FOLDER
        - mvn package
    - stage: lab4
      jdk: openjdk13
      env: FOLDER=lab4
      script:
        - cd $FOLDER
        - mvn package
    - stage: lab5
      jdk: openjdk13
      env: FOLDER=lab5
      script:
        - cd $FOLDER
        - mvn package
    - stage: lab6
      env:
        - FOLDER=lab6
      install:
        - wget https://github.com/forax/java-next/releases/download/untagged-c59655314c1759142c15/jdk-14-loom-linux.tar.gz
        - tar xvf jdk-14-loom-linux.tar.gz
        - export JAVA_HOME=`pwd`/jdk-14-loom
        - echo $JAVA_HOME
      script:
        - cd $FOLDER
        - mvn package
